### ISSUE TITLE
User can view items by new

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/not-etsy#1]
## 💰 Feature

User can view items by new

## 🗒️ Notes

This will require me to query the database so I can render cards for each item added recently.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/70028619/102947669-b3e7a880-4478-11eb-806e-3ceb4b172594.png)

## ✅ Tasks

- [x] Create base elements for project (Create html, css, js, and other files and install modules)
- [x] Create server in 'server.js' using express
- [x] Create database using postgresql
- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Refactor the component to fetch the data from the server.
- [x] Complete the component with an initial state of dread and an event handler for onClick
- [x] Update bootstrap to 4.5
- [x] remove reset css styling, bootstrap does it automatically
- [x] put title class on h1 element (for header)
- [x] change theShade class to kebab-case for css
- [x] Remove commented out code
