### ISSUE TITLE
User can view details of an item

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/not-etsy#2]
## 💰 Feature

User can view details of an item.

## 🗒️ Notes

This will require me to query the database to find the item that was selected and render the item based on the customization ID.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/70028619/103247632-622d9b00-491c-11eb-9f0e-34c0eecb7c42.png)

## ✅ Tasks

- [x]  Render the card with the title, image, price, and description.
- [x] Add a form for the custom details input.
- [x] Add hash routing to go back and forth between pages and users can select item to view details.
- [x] Remove Id retrieval from parse route.
- [x] Destructure props in new-items.
- [x] Look up order by in SQL
- [x] Change custom1 to Details and add functionality to that page to render the forms properly
- [x] Adjust how to access prodId from renderPage in app
- [x] Restructure NewItems component to render items inside itself.
- [x] Create a lib directory for helper functions and put parse route inside.
