### ISSUE TITLE
User can add items to their cart

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/not-etsy#3]
## 💰 Feature

User can add items to their cart

## 🗒️ Notes

This will require me to create a handler for the add item button, as well as create a popup and add an item count to the cart that lets the user know the item has successfully added.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/70028619/103364371-74215200-4a72-11eb-9745-6ddabfa5aea9.png)

## ✅ Tasks

- [x] Add new table in data.sql for cart. Needs all data from product table for product plus form data (customizations).
- [x] Add post request in index.js
- [x] test post with HTTPie
- [x] Add button for user to add items to cart.
- [x] Add a quantity button that determines the number of items being added to the cart.
- [x] Add fetch request that sends the data to the server to put in the database. 
- [x] Fix object.assign, pass it an empty object first.
- [x] Adjust conditions to handle quantity first, like a guard.
- [x] Add name prop to all inputs
- [x] When creating a clean state just create a completely blank slate.
- [x] Put all forms in their own component.
- [x] Use math.max instead of conditional logic to compare array sizes
- [x] Clean up post route by simplifying the code.
