### ISSUE TITLE
User can view their cart

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/not-etsy#4]
## 💰 Feature

User can view their cart

## 🗒️ Notes

This will require me to render a page that shows all the items in the users cart.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/70028619/103710287-87985580-4f69-11eb-86f0-b23f6228bc37.png)

## ✅ Tasks

- [x] Add route to retrieve the users cart.
- [x] Test if cartId is valid throw new client error if not
- [x] Test if cart exists return null if not
- [x] If cartId is valid and cart exists query the db for the items in the cart.
- [x] Use HTTPie to confirm data retrieved
- [x] Confirm all back end code works properly
- [x] Create Hash route for cart
- [x] Create new component for listing all cart items
- [x] Create cart button
- [x] Create menu
