### ISSUE TITLE
User can remove items from cart

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/not-etsy#5]
## 💰 Feature

User can remove items from cart

## 🗒️ Notes

This will require me to create a handler for clicking the trash can icon that deletes the item from the cart and re-renders the page.

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/70028619/104041563-184f7b00-518e-11eb-9559-71f4c646b518.png)

## ✅ Tasks

- [x] Create route to delete items from cart in database
- [x] Test route with HTTPie
- [x] Create fetch request for delete
- [x] Add functionality to delete button
- [x] Test and confirm proper operation of all delete functions in code
