### ISSUE TITLE
User can change quantity of items in cart

### ISSUE THREAD

**Issue by Mrkalen** [Mrkalen/not-etsy#6]
## 💰 Feature

User can change quantity of items in cart

## 🗒️ Notes

This will require me to create a form that determines the number of items in the cart. As well as create a button to refresh the number of items in the cart

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/70028619/103932458-b4b64680-50d6-11eb-8f55-4a057b531976.png)

## ✅ Tasks

- [x] Add functionality to quantity dropdown
- [x] Add route to server to update quantity
- [x] Add fetch request to update quantity
- [x] Update state to adjust new quantity
- [x] Confirm Quantity has changed in price
